# Version Comparsion

set(PACKAGE_VERSION 3.1750.1738)

if ("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL 3 AND
    "${PACKAGE_FIND_VERSION_MINOR}" EQUAL 1750)
    set(PACKAGE_VERSION_COMPATIBLE 1)

    if ("${PACKAGE_FIND_VERSION_PATCH}" EQUAL 1738)
        set(PACKAGE_VERSION_EXACT 1)
    endif ()
endif ()