# Version Comparsion

set(PACKAGE_VERSION 3.2272.32)

if ("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL 3 AND
    "${PACKAGE_FIND_VERSION_MINOR}" EQUAL 2272)
    set(PACKAGE_VERSION_COMPATIBLE 1)

    if ("${PACKAGE_FIND_VERSION_PATCH}" EQUAL 32)
        set(PACKAGE_VERSION_EXACT 1)
    endif ()
endif ()