/* ---------------------------------------------------------------------------
** Team Bear King
** © 2015 DigiPen Institute of Technology, All Rights Reserved.
**
** UrsineConsoleColor.h
**
** Author:
** - Austin Brunkhorst - A.Brunkhorst@digipen.edu
**
** Contributors:
** - <list in same format as author if applicable>
** -------------------------------------------------------------------------*/

#pragma once

#include "MacroUtils.h"

namespace Ursine
{
    enum ConsoleColor
    {
        CC_TEXT_BLACK = 0,
        CC_TEXT_BRIGHTER = 0x0008,
        CC_TEXT_RED = 0x0004,
        CC_TEXT_BRIGHT_RED = CC_TEXT_RED | CC_TEXT_BRIGHTER,
        CC_TEXT_GREEN = 0x0002,
        CC_TEXT_BRIGHT_GREEN = CC_TEXT_GREEN | CC_TEXT_BRIGHTER,
        CC_TEXT_BLUE = 0x0001,
        CC_TEXT_BRIGHT_BLUE = CC_TEXT_BLUE | CC_TEXT_BRIGHTER,
        CC_TEXT_WHITE = CC_TEXT_RED | CC_TEXT_GREEN | CC_TEXT_BLUE,
        CC_TEXT_BRIGHT_WHITE = CC_TEXT_WHITE | CC_TEXT_BRIGHTER,
        CC_TEXT_YELLOW = CC_TEXT_RED | CC_TEXT_GREEN,
        CC_TEXT_BRIGHT_YELLOW = CC_TEXT_YELLOW | CC_TEXT_BRIGHTER,
        CC_TEXT_PURPLE = CC_TEXT_RED | CC_TEXT_BLUE,
        CC_TEXT_BRIGHT_PURPLE = CC_TEXT_PURPLE | CC_TEXT_BRIGHTER,
        CC_TEXT_AQUA = CC_TEXT_GREEN | CC_TEXT_BLUE,
        CC_TEXT_BRIGHT_AQUA = CC_TEXT_AQUA | CC_TEXT_BRIGHTER,
        CC_BACKGROUND_BLACK = 0,
        CC_BACKGROUND_BRIGHTER = 0x0080,
        CC_BACKGROUND_RED = 0x0040,
        CC_BACKGROUND_BRIGHT_RED = CC_BACKGROUND_RED | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_GREEN = 0x0020,
        CC_BACKGROUND_BRIGHT_GREEN = CC_BACKGROUND_GREEN | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_BLUE = 0x0010,
        CC_BACKGROUND_BRIGHT_BLUE = CC_BACKGROUND_BLUE | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_WHITE = CC_BACKGROUND_RED | CC_BACKGROUND_GREEN | CC_BACKGROUND_BLUE,
        CC_BACKGROUND_BRIGHT_WHITE = CC_BACKGROUND_WHITE | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_YELLOW = CC_BACKGROUND_RED | CC_BACKGROUND_GREEN,
        CC_BACKGROUND_BRIGHT_YELLOW = CC_BACKGROUND_YELLOW | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_PURPLE = CC_BACKGROUND_RED | CC_BACKGROUND_BLUE,
        CC_BACKGROUND_BRIGHT_PURPLE = CC_BACKGROUND_PURPLE | CC_BACKGROUND_BRIGHTER,
        CC_BACKGROUND_AQUA = CC_BACKGROUND_GREEN | CC_BACKGROUND_BLUE,
        CC_BACKGROUND_BRIGHT_AQUA = CC_BACKGROUND_AQUA | CC_BACKGROUND_BRIGHTER,
    };
}