

ENUMERATE(COMMAND_START)

ENUMERATE(FIRE_START)
ENUMERATE(FIRE_END)
ENUMERATE(LOOK_COMMAND)
ENUMERATE(JUMP_COMMAND)
ENUMERATE(SWAP_COMMAND)
ENUMERATE(RELOAD_COMMAND)
ENUMERATE(INTERACT_COMMAND)
ENUMERATE(MOVEMENT)
ENUMERATE(MOVEMENT2)

ENUMERATE(COMMAND_END)
